<?php

// Code generated by gen:dao. DO NOT EDIT.

declare(strict_types=1);

namespace App\Repositories;

use App\Entities\User;
use Flame\Contracts\RepositoryInterface;
use Exception;

class UserRepository extends CurdRepository implements RepositoryInterface
{
    
}
